/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이메일·비밀번호 회원가입
     * @description 새 사용자를 만들고 즉시 로그인 세션을 발급합니다.
     *     이메일 인증과 비밀번호 재설정은 MVP에서 제공하지 않습니다.
     */
    post: operations['registerUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그인
     * @description 이메일과 비밀번호를 검증하고 쿠키 세션을 발급합니다.
     */
    post: operations['createSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 현재 세션 조회 */
    get: operations['getCurrentSession'];
    put?: never;
    post?: never;
    /** 로그아웃 */
    delete: operations['deleteCurrentSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 계정 조회 */
    get: operations['getMe'];
    put?: never;
    post?: never;
    /**
     * 계정과 전체 기록 즉시 삭제
     * @description 계정, 피부 보고 원문, 구조화 결과, 관리 결과, 경과, Push 구독 및 활성 세션을
     *     복구 불가능하게 삭제합니다. 다른 사용자와 연결되지 않은 집계 지표에는 피부 상세정보가 없습니다.
     */
    delete: operations['deleteMe'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/onboarding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 온보딩 완료
     * @description 최신 필수 동의와 기본 피부 점호 시각을 저장합니다.
     *
     *     [변경] 동의는 2건입니다.
     *     1. 개인정보·민감정보 수집·이용 동의 (필수, `sensitiveDataConsent`)
     *     2. 알림 수신 동의 (알림을 켜는 경우에만 필수, `notificationConsent`)
     *
     *     [변경] 기본 피부 점호 시각(`notificationTime`)을 **온보딩 마지막 화면에서 한 번 설정**합니다.
     *     화면 구성은 시간 피커(기본 17:30) + `알림을 받지 않을게요` + `시작하기` 입니다.
     *
     *     - `시작하기`를 누른 경우: `notificationEnabled: true`, 피커 값이 `notificationTime`,
     *       `notificationConsent: true`. 이 시점에 OS 알림 권한을 요청하고 그 결과를 `notificationPermission`에 담습니다.
     *     - `알림을 받지 않을게요`를 누른 경우: `notificationEnabled: false`.
     *       `notificationConsent`는 생략하거나 false이며 OS 권한을 요청하지 않습니다.
     *       이때도 서버는 `notificationTime`을 기본값 17:30으로 저장합니다.
     *       경과 입력 가능 시점(`PendingFollowUp.availableFrom`) 계산에 이 값이 필요하기 때문입니다.
     *
     *     `notificationEnabled`가 true인데 `notificationConsent`가 true가 아니면 422로 거부합니다.
     */
    put: operations['completeOnboarding'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/notification-settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 알림 설정 조회 */
    get: operations['getNotificationSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 알림 사용 여부 변경 (시각 변경은 P1)
     * @description 설정 화면에서 알림을 켜고 끕니다.
     *
     *     [P0] `enabled`, `consent`
     *     [P1] `time` — 기능명세서 5.2 "알림 시간 변경"이 P1이므로 P0 구현에서는 이 필드를 받지 않아도 됩니다.
     *          P0에서 요청에 `time`이 들어오면 422(code: `FEATURE_NOT_AVAILABLE`)로 거부하세요.
     *          기본 피부 점호 시각의 최초 설정은 `PUT /me/onboarding`에서 처리합니다.
     *
     *     정책
     *     - `enabled`를 false → true로 바꾸려면 `consent.agreed`가 true여야 합니다. 아니면 422입니다.
     *     - 알림은 하루 최대 한 번만 발송하며, 미완료 경과가 있으면 피부 점호보다 경과 확인 알림이 우선합니다.
     *     - 알림을 꺼도 홈에서 직접 기능을 이용할 수 있고, 경과 입력 가능 시점도 그대로 유지됩니다.
     *     - (P1) `time`을 변경하면 다음 발송분부터 적용합니다. 이미 발송된 당일 알림은 재발송하지 않습니다.
     */
    patch: operations['updateNotificationSettings'];
    trace?: never;
  };
  '/push-subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Web Push 구독 등록
     * @description 브라우저 PushSubscription을 현재 사용자에게 등록합니다.
     *     endpoint는 capability URL이므로 응답·로그에 전체 값을 노출하지 않아야 합니다.
     */
    post: operations['createPushSubscription'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/push-subscriptions/{subscriptionId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subscriptionId: components['parameters']['SubscriptionId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Web Push 구독 해제 */
    delete: operations['deletePushSubscription'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/home': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 홈 화면 정보 조회
     * @description 미완료 경과 중 가장 오래된 한 건, 오늘 상태, 최근 기록 한 건을 반환합니다.
     */
    get: operations['getHome'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/daily-check-ins/{date}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Asia/Seoul 기준 날짜 */
        date: components['parameters']['CheckInDate'];
      };
      cookie?: never;
    };
    get?: never;
    /**
     * 오늘 불편 없음 저장
     * @description Asia/Seoul 기준 오늘 날짜만 허용합니다. 이후 같은 날 피부 보고가 확정되면
     *     서버가 이 상태를 SKIN_REPORT로 교체합니다. 미응답은 불편 없음으로 저장하지 않습니다.
     */
    put: operations['saveNoDiscomfortCheckIn'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reference-data/skin-report-options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 피부 보고 선택값 조회
     * @description 프론트엔드 라벨과 API enum 값을 연결하는 버전 있는 목록입니다.
     *
     *     [중요] 겉모습(`appearances`)은 아직 6개 확정 전이라 스키마에 enum이 없습니다.
     *     프론트엔드는 겉모습 선택지를 하드코딩하지 말고 반드시 이 응답의 `appearances`를 사용하세요.
     */
    get: operations['getSkinReportOptions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/report-interpretations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 한 문장 피부 보고 구조화
     * @description 원문과 사용자가 직접 선택한 보조 입력을 구조화합니다. 직접 선택값이 AI 추출보다 우선합니다.
     *     이 호출은 정식 피부 보고를 만들지 않습니다. AI가 실패해도 200 응답의 FAILED 상태와
     *     수동 선택값을 반환하여 사용자가 직접 입력을 계속할 수 있게 합니다.
     */
    post: operations['createReportInterpretation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/skin-reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 피부 기록 목록 조회 */
    get: operations['listSkinReports'];
    put?: never;
    /**
     * 최종 피부 보고와 결과 생성
     * @description 사용자 최종 확인값을 저장하고 고정 규칙으로 결과 유형을 결정합니다.
     *     SELF_CARE_GUIDE이면 규칙 조회와 AI 설명을 동기 처리합니다. AI 설명 실패 시에도
     *     규칙의 기본 문구로 201을 반환합니다. 같은 날 한 건만 허용하며 Idempotency-Key로 중복을 방지합니다.
     *
     *     [신규] SELF_CARE_GUIDE 결과에는 추천 성분(`recommendedIngredients`)과
     *     가이드 6개 섹션의 제목·설명(`guideSections`)이 포함됩니다.
     *     추천 성분은 관리 규칙표에서 조회한 값만 사용하며 AI가 새로 만들지 않습니다.
     *     특정 제품·브랜드·의약품은 반환하지 않습니다.
     */
    post: operations['createSkinReport'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/skin-reports/{reportId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    /**
     * 피부 기록 상세 조회
     * @description 다른 사용자의 reportId는 존재 여부를 노출하지 않고 404로 응답합니다.
     */
    get: operations['getSkinReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/skin-reports/{reportId}/care-guide-generations': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 관리 설명 재생성
     * @description 최초 aiGenerationStatus가 FALLBACK인 SELF_CARE_GUIDE 보고에 한해 정확히 한 번 허용합니다.
     *     규칙 ID, 버전, 허용·금지 행동, 추천 성분은 바꾸지 않고 설명만 다시 생성합니다.
     */
    post: operations['retryCareGuideGeneration'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/skin-reports/{reportId}/follow-up': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    /** 다음 날 경과 조회 */
    get: operations['getFollowUp'];
    /**
     * 다음 날 경과 저장
     * @description 입력 가능 시점부터 48시간 안에 한 번만 저장합니다. 같은 본문 재요청은 기존 값을 반환하고,
     *     다른 본문으로 덮어쓰려 하면 409를 반환합니다. 의료진의 진단·처방 내용은 받지 않습니다.
     *
     *     [변경] 결과 유형과 무관하게 피부 변화(`skinChange`)와 행동 실행 여부(`actionCompletion`)를 받습니다.
     *     CLINICIAN_CHECK인 경우 여기에 의료진 확인 여부(`clinicianCheckStatus`)가 추가됩니다.
     */
    put: operations['saveFollowUp'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/analytics-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 측정 이벤트 묶음 저장
     * @description 원문, 얼굴 부위, 겉모습, 불편, 군번, 부대명, 위치 및 의료진 확인 내용을 받지 않습니다.
     *     서버는 허용된 이벤트명과 속성만 저장하고 그 밖의 속성을 거부합니다.
     */
    post: operations['createAnalyticsEvents'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    AuthSession: {
      user: components['schemas']['User'];
      /** @description 상태 변경 요청의 X-CSRF-Token 값 */
      csrfToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    User: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      email: string;
      signupcompleted: boolean;
      /** Format: date-time */
      readonly createdAt: string;
    };
    OnboardingRequest: {
      /**
       * @description 개인정보·민감정보 수집·이용 동의 버전 (동의 1/2)
       * @example 2026-08-16
       */
      consentVersion: string;
      /**
       * @description 개인정보·민감정보 수집·이용 동의 (필수, 동의 1/2)
       * @constant
       */
      sensitiveDataConsent: true;
      notificationEnabled: boolean;
      notificationPermission: components['schemas']['NotificationPermission'];
      notificationTime?: components['schemas']['NotificationTime'];
      /**
       * @description 알림 수신 동의. `시작하기`로 알림을 켜는 경우 필수이며 true여야 합니다.
       *     시간 피커 화면에서 동의와 시각 설정이 한 번에 확정됩니다.
       */
      notificationConsent?: boolean;
      /** @example 2026-08-16 */
      notificationConsentVersion?: string;
    };
    Onboarding: {
      consentVersion: string;
      /** Format: date-time */
      consentedAt: string;
      notificationEnabled: boolean;
      notificationPermission: components['schemas']['NotificationPermission'];
      notificationTime: components['schemas']['NotificationTime'];
      notificationConsent: components['schemas']['NotificationConsent'];
      /** Format: date-time */
      completedAt: string;
    };
    NotificationConsent: {
      agreed: boolean;
      version: string;
      /**
       * Format: date-time
       * @description 동의하지 않았거나 철회한 경우 null
       */
      agreedAt: string | null;
    };
    NotificationConsentInput: {
      agreed: boolean;
      version: string;
    };
    /** @enum {string} */
    NotificationPermission: 'DEFAULT' | 'GRANTED' | 'DENIED' | 'UNSUPPORTED';
    /**
     * @description 기본 피부 점호 시각입니다. Asia/Seoul 기준 24시간 표기 HH:mm이며 기본값은 17:30입니다.
     *
     *     온보딩 마지막 화면("기본 피부점호 시간을 설정해주세요")의 시간 피커에서 한 번 설정합니다.
     *     설정 화면에서 나중에 바꾸는 기능은 P1입니다.
     *
     *     이 값은 두 곳에 쓰입니다.
     *     1. 매일 피부 점호 / 경과 확인 알림 발송 시각
     *     2. 다음 날 경과 입력 가능 시점 (`PendingFollowUp.availableFrom`)
     *
     *     알림을 끈 사용자도 2번 때문에 값을 가집니다(기본 17:30).
     *
     *     [TODO] 피커의 분 단위 간격이 디자인에서 확정되지 않았습니다.
     *     10분 단위로 확정되면 pattern을 '^([01][0-9]|2[0-3]):[0-5]0$' 로 좁히세요.
     * @default 17:30
     * @example 17:30
     */
    NotificationTime: string;
    NotificationSettings: {
      enabled: boolean;
      time: components['schemas']['NotificationTime'];
      /** @constant */
      timezone: 'Asia/Seoul';
      /**
       * @description 설정 화면에서 `time` 변경 UI를 노출할지 여부. P0 배포에서는 false입니다.
       * @default false
       */
      timeEditable: boolean;
      permission: components['schemas']['NotificationPermission'];
      consent: components['schemas']['NotificationConsent'];
      activeSubscriptionCount: number;
    };
    CreatePushSubscriptionRequest: {
      /** Format: uri */
      endpoint: string;
      /** Format: date-time */
      expirationTime: string | null;
      keys: {
        p256dh: string;
        auth: string;
      };
      userAgent: string;
    };
    PushSubscription: {
      /** Format: uuid */
      id: string;
      /** @description endpoint의 비가역 지문 */
      endpointFingerprint: string;
      active: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Home: {
      /** Format: date */
      serverDate: string;
      /** @enum {string} */
      priority: 'FOLLOW_UP' | 'TODAY_CHECK_IN' | 'RECENT_RECORD' | 'EMPTY';
      pendingFollowUp: components['schemas']['PendingFollowUp'] | null;
      today: components['schemas']['DailyCheckIn'] | null;
      recentReport: components['schemas']['SkinReportSummary'] | null;
    };
    DailyCheckIn: {
      /** Format: date */
      date: string;
      /** @enum {string} */
      state: 'NO_DISCOMFORT' | 'SKIN_REPORT';
      /** Format: uuid */
      reportId?: string | null;
      /** Format: date-time */
      updatedAt: string;
    };
    ManualSelections: {
      primaryArea?: components['schemas']['BodyArea'];
      appearances?: components['schemas']['AppearanceSelection'];
      sensations?: components['schemas']['SensationSelection'];
    };
    InterpretReportRequest: {
      rawText: string;
      manualSelections?: components['schemas']['ManualSelections'];
    };
    ReportInterpretation: {
      /** @enum {string} */
      processingStatus: 'SUCCESS' | 'FAILED';
      proposed: components['schemas']['StructuredReportDraft'];
      missingFields: (
        'PRIMARY_AREA' | 'APPEARANCES' | 'SENSATIONS' | 'SITUATIONS' | 'CARE_AVAILABILITY'
      )[];
      ambiguities: {
        field: string;
        text: string;
      }[];
      /** @enum {string|null} */
      failureCode?: null | 'AI_TIMEOUT' | 'AI_INVALID_OUTPUT' | 'AI_UNAVAILABLE';
    };
    StructuredReportDraft: {
      primaryArea: components['schemas']['BodyArea'] | null;
      otherAreasNote: string | null;
      appearances: components['schemas']['AppearanceSelection'];
      sensations: components['schemas']['SensationSelection'];
      situations: components['schemas']['SituationSelection'];
      careAvailability: components['schemas']['CareAvailability'] | null;
    };
    CreateSkinReportRequest: {
      /**
       * Format: date
       * @description Asia/Seoul 기준 오늘
       */
      reportDate: string;
      rawText: string;
      confirmed: components['schemas']['ConfirmedStructuredReport'];
      preCareChecks: components['schemas']['PreCareCheckSelection'];
    };
    ConfirmedStructuredReport: {
      primaryArea: components['schemas']['BodyArea'];
      otherAreasNote: string | null;
      appearances: components['schemas']['AppearanceSelection'];
      sensations: components['schemas']['SensationSelection'];
      situations: components['schemas']['SituationSelection'];
      careAvailability: components['schemas']['CareAvailability'];
    };
    SkinReportSummary: {
      /** Format: uuid */
      id: string;
      /** Format: date */
      reportDate: string;
      primaryArea: components['schemas']['BodyArea'];
      appearances: components['schemas']['AppearanceSelection'];
      sensations: components['schemas']['SensationSelection'];
      situations: components['schemas']['SituationSelection'];
      resultType: components['schemas']['ResultType'];
      status: components['schemas']['ReportStatus'];
      skinChange?: components['schemas']['SkinChange'] | null;
    };
    SkinReportDetail: {
      /** Format: uuid */
      id: string;
      /** Format: date */
      reportDate: string;
      primaryArea: components['schemas']['BodyArea'];
      appearances: components['schemas']['AppearanceSelection'];
      sensations: components['schemas']['SensationSelection'];
      situations: components['schemas']['SituationSelection'];
      resultType: components['schemas']['ResultType'];
      status: components['schemas']['ReportStatus'];
      skinChange?: components['schemas']['SkinChange'] | null;
      rawText: string;
      confirmed: components['schemas']['ConfirmedStructuredReport'];
      preCareChecks: components['schemas']['PreCareCheckSelection'];
      careResult: components['schemas']['CareResult'];
      followUp: components['schemas']['FollowUp'] | null;
      /** Format: date-time */
      createdAt: string;
    } & (unknown & unknown);
    CareResult: {
      resultType: components['schemas']['ResultType'];
      matchedRuleIds: string[];
      ruleVersion: string;
      /**
       * @description 결과 카드에 노출할 6개 섹션의 제목과 설명입니다.
       *     표시 순서는 배열 순서를 따릅니다. 각 섹션의 본문은 아래 대응 필드에서 읽습니다.
       *
       *     | key | 대응 본문 필드 |
       *     |-----|----------------|
       *     | CURRENT_SUMMARY | summary |
       *     | DO_TODAY | doToday |
       *     | AVOID_TODAY | avoidToday |
       *     | SIMILAR_EXPERIENCE | similarExperience |
       *     | CHECK_NEXT | checkNext |
       *     | RECOMMENDED_INGREDIENTS | recommendedIngredients |
       */
      guideSections: components['schemas']['GuideSection'][];
      /** @description 현재 기록 요약 (최대 2문장) */
      summary: string;
      /** @description 오늘 할 일. 규칙의 allowedActions 범위 안에서만 생성합니다. */
      doToday: string[];
      /** @description 오늘 피할 일. 규칙의 prohibitedActions 범위 안에서만 생성합니다. */
      avoidToday: string[];
      /** @description 다음에 확인할 변화. 규칙의 monitorItems 범위 안에서만 생성합니다. */
      checkNext: string[];
      /**
       * @description 관리 규칙표에서 조회한 성분 정보만 반환합니다.
       *     AI가 새로운 성분을 만들지 않으며, 특정 제품·브랜드·의약품은 반환하지 않습니다.
       *     규칙에 해당 성분이 없으면 빈 배열입니다.
       */
      recommendedIngredients: components['schemas']['RecommendedIngredient'][];
      /** @description 안내가 달라진 이유. 적용된 직전 상황과 현재 관리 상태 태그입니다. */
      reasonTags: string[];
      clinicianMessage?: string | null;
      similarExperience: components['schemas']['SimilarExperience'] | null;
      /** @enum {string} */
      aiGenerationStatus: 'GENERATED' | 'FALLBACK' | 'NOT_APPLICABLE';
      /** Format: date-time */
      generatedAt: string;
      retryUsed: boolean;
    } & (unknown & unknown);
    GuideSection: {
      /** @enum {string} */
      key:
        | 'CURRENT_SUMMARY'
        | 'DO_TODAY'
        | 'AVOID_TODAY'
        | 'SIMILAR_EXPERIENCE'
        | 'CHECK_NEXT'
        | 'RECOMMENDED_INGREDIENTS';
      /** @example 오늘 할 일 */
      title: string;
      /**
       * @description 섹션이 무엇을 뜻하는지 알려주는 한 줄 설명. 관리 규칙표에서 관리합니다.
       * @example 지금 상태에서 오늘 안에 해볼 수 있는 행동입니다.
       */
      description: string;
      /**
       * @description 대응 본문이 비어 있어 섹션을 접힌 상태로 표시해야 하는 경우 true
       * @default false
       */
      empty: boolean;
    };
    RecommendedIngredient: {
      /** @example ING_PANTHENOL */
      id: string;
      /** @example 판테놀 */
      name: string;
      /** @description 관리 규칙표에 저장된 중립적 설명. 효능 보장, 치료 표현, 제품 추천을 포함하지 않습니다. */
      description: string;
      /** @description 주의 문구. 없으면 null입니다. */
      cautionNote?: string | null;
      /** @description 이 성분을 반환한 관리 규칙 ID. matchedRuleIds의 부분집합이어야 합니다. */
      sourceRuleIds: string[];
    };
    SimilarExperience: {
      /** Format: uuid */
      reportId: string;
      /** Format: date */
      reportDate: string;
      /**
       * @description 같은 대표 부위 +3, 같은 직전 상황 항목당 +2, 같은 겉모습 항목당 +1,
       *     같은 느껴지는 불편 항목당 +1, 같은 현재 관리 상태 +1.
       *     총 5점 이상인 COMPLETED 기록 중 최고점 1건만 반환합니다. 동점이면 최근 기록이 우선합니다.
       */
      similarityScore: number;
      /**
       * @description AI를 다시 호출하지 않고 구조화 데이터를 고정 문장 형식으로 채운 문구입니다.
       *     인과관계, 치료 효과, 확률·배수 표현을 포함하지 않습니다.
       */
      displayText: string;
      skinChange: components['schemas']['SkinChange'];
    };
    PendingFollowUp: {
      /** Format: uuid */
      reportId: string;
      /** Format: date */
      reportDate: string;
      /**
       * Format: date-time
       * @description 다음 날, 사용자가 온보딩에서 설정한 피부 점호 시각(NotificationSettings.time)입니다.
       *     알림을 꺼 둔 사용자도 이 값을 가지며 기본값은 17:30입니다.
       */
      availableFrom: string;
      /**
       * Format: date-time
       * @description availableFrom + 48시간
       */
      expiresAt: string;
      resultType: components['schemas']['ResultType'];
    };
    SaveFollowUpRequest:
      | components['schemas']['SelfCareFollowUpRequest']
      | components['schemas']['ClinicianFollowUpRequest'];
    SelfCareFollowUpRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'SELF_CARE';
      skinChange: components['schemas']['SkinChange'];
      actionCompletion: components['schemas']['ActionCompletion'];
    };
    ClinicianFollowUpRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'CLINICIAN_CHECK';
      skinChange: components['schemas']['SkinChange'];
      actionCompletion: components['schemas']['ActionCompletion'];
      clinicianCheckStatus: components['schemas']['ClinicianCheckStatus'];
    };
    FollowUp:
      components['schemas']['SelfCareFollowUp'] | components['schemas']['ClinicianFollowUp'];
    SelfCareFollowUp: {
      /** Format: uuid */
      reportId: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'SELF_CARE';
      skinChange: components['schemas']['SkinChange'];
      actionCompletion: components['schemas']['ActionCompletion'];
      /** Format: date-time */
      submittedAt: string;
    };
    ClinicianFollowUp: {
      /** Format: uuid */
      reportId: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'CLINICIAN_CHECK';
      skinChange: components['schemas']['SkinChange'];
      actionCompletion: components['schemas']['ActionCompletion'];
      clinicianCheckStatus: components['schemas']['ClinicianCheckStatus'];
      /** Format: date-time */
      submittedAt: string;
    };
    /**
     * @description 다 실행했어요 / 일부만 실행했어요 / 실행하지 못했어요
     * @enum {string}
     */
    ActionCompletion: 'MOSTLY_DONE' | 'PARTLY_DONE' | 'NOT_DONE';
    /**
     * @description 의무실·의료진에게 확인했어요 / 아직 확인하지 못했어요 / 기록하지 않을게요
     * @enum {string}
     */
    ClinicianCheckStatus: 'CHECKED' | 'NOT_YET' | 'PREFER_NOT_TO_RECORD';
    SkinReportList: {
      data: components['schemas']['SkinReportSummary'][];
      pagination: components['schemas']['CursorPage'];
    };
    CursorPage: {
      nextCursor: string | null;
      hasMore: boolean;
      limit: number;
    };
    AnalyticsEventInput: {
      /** Format: uuid */
      eventId: string;
      /** @enum {string} */
      name:
        | 'ONBOARDING_COMPLETED'
        | 'REPORT_STARTED'
        | 'INPUT_ASSIST_OPENED'
        | 'AI_STRUCTURING_SUCCEEDED'
        | 'AI_STRUCTURING_FAILED'
        | 'REPORT_SUBMITTED'
        | 'CARE_RESULT_VIEWED'
        | 'FOLLOW_UP_SUBMITTED'
        | 'SIMILAR_EXPERIENCE_VIEWED'
        | 'RECOMMENDED_INGREDIENTS_VIEWED'
        | 'NOTIFICATION_TIME_SET';
      /** Format: date-time */
      occurredAt: string;
      properties?: {
        durationMs?: number;
        inputAssistUsed?: boolean;
        resultType?: components['schemas']['ResultType'];
        aiSucceeded?: boolean;
        ingredientCount?: number;
        usedDefaultTime?: boolean;
      };
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail: string;
      /** Format: uri-reference */
      instance?: string;
      /** @example VALIDATION_ERROR */
      code: string;
      requestId: string;
      errors?: {
        field: string;
        code: string;
        message: string;
      }[];
    };
    /** @enum {string} */
    BodyArea:
      | 'LEFT_FOREHEAD'
      | 'CENTER_FOREHEAD'
      | 'RIGHT_FOREHEAD'
      | 'NOSE'
      | 'LEFT_CHEEK'
      | 'RIGHT_CHEEK'
      | 'AROUND_MOUTH'
      | 'LEFT_CHIN'
      | 'RIGHT_CHIN'
      | 'LEFT_JAWLINE'
      | 'RIGHT_JAWLINE'
      | 'NECK'
      | 'OTHER';
    /**
     * @description [TODO] 겉모습 선택지 6개가 미확정입니다. enum이 비어 있으므로 서버는 참조 데이터
     *     (/reference-data/skin-report-options 의 appearances)에 있는 value만 허용하고
     *     그 밖의 값은 422로 거부해야 합니다.
     */
    AppearanceSelection: string[];
    /**
     * @description [변경] v2에서 이 필드의 의미가 "감각"에서 "불편 유형"으로 바뀌었습니다.
     *     관리 규칙 매칭의 주 축이며, 유사도 계산에서 항목당 +1점입니다.
     */
    SensationSelection: ('REDNESS' | 'EXCESS_SEBUM' | 'BREAKOUT')[];
    /** @description 유사도 계산에서 항목당 +2점으로 가장 큰 가중치를 가집니다. */
    SituationSelection: (
      | 'PROTECTIVE_GEAR_OR_MASK'
      | 'SHAVING'
      | 'SQUEEZED_ACNE'
      | 'NEW_PRODUCT'
      | 'SWEAT_OR_SEBUM'
      | 'NONE_RECALLED'
    )[];
    /** @enum {string} */
    CareAvailability:
      | 'BEFORE_WASH_CAN_WASH_LATER'
      | 'ALREADY_WASHED'
      | 'CAN_CARE_BEFORE_SLEEP'
      | 'ADDITIONAL_CARE_DIFFICULT';
    /**
     * @description NONE만 선택하면 SELF_CARE_GUIDE, 그 밖의 항목이 하나라도 있으면 CLINICIAN_CHECK입니다.
     *     AI 추출값이 아니라 사용자가 최종 확인한 값으로만 분기합니다.
     */
    PreCareCheckSelection: (
      'SPREADING_RAPIDLY' | 'SEVERE_PAIN_HEAT_SWELLING' | 'PUS_OOZING_BLISTER' | 'NONE'
    )[];
    /** @enum {string} */
    ResultType: 'SELF_CARE_GUIDE' | 'CLINICIAN_CHECK';
    /** @enum {string} */
    ReportStatus: 'FOLLOW_UP_PENDING' | 'COMPLETED' | 'EXPIRED';
    /** @enum {string} */
    SkinChange: 'IMPROVED' | 'SIMILAR' | 'WORSENED';
    SkinReportOptions: {
      /** @example 2026-08-16 */
      version: string;
      areas: components['schemas']['OptionList'];
      appearances: components['schemas']['OptionList'];
      sensations: components['schemas']['OptionList'];
      situations: components['schemas']['OptionList'];
      careAvailability: components['schemas']['OptionList'];
      preCareChecks: components['schemas']['OptionList'];
      guideSections: components['schemas']['GuideSection'][];
    };
    OptionList: {
      value: string;
      label: string;
    }[];
  };
  responses: {
    /** @description 요청 문법 또는 쿼리 매개변수 오류 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 세션이 없거나 만료됨 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "https://api.example.invalid/problems/authentication-required",
         *       "title": "인증 필요",
         *       "status": 401,
         *       "detail": "다시 로그인해 주세요.",
         *       "code": "AUTHENTICATION_REQUIRED",
         *       "requestId": "req_01J5D8M7Q4"
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 리소스가 없거나 현재 사용자에게 속하지 않음 */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 중복 또는 현재 상태와 충돌 */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 문법은 맞지만 필드 또는 상태 전이 검증 실패 */
    UnprocessableEntity: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 요청 제한 초과 */
    TooManyRequests: {
      headers: {
        /** @description 재시도까지 기다릴 초 */
        'Retry-After'?: number;
        'X-RateLimit-Limit'?: number;
        'X-RateLimit-Remaining'?: number;
        /** @description 제한 해제 Unix timestamp */
        'X-RateLimit-Reset'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description 필수 내부 서비스 또는 규칙 조회를 사용할 수 없음 */
    ServiceUnavailable: {
      headers: {
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    ReportId: string;
    SubscriptionId: string;
    /** @description Asia/Seoul 기준 날짜 */
    CheckInDate: string;
    /** @description createdAt과 id를 포함한 불투명 커서 */
    Cursor: string;
    Limit: number;
    /** @description 같은 사용자와 작업 범위에서 24시간 보관하는 UUID */
    IdempotencyKey: string;
    DeleteConfirmation: 'delete-account';
  };
  requestBodies: never;
  headers: {
    /** @description 브라우저 세션 쿠키 */
    SessionCookie: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  registerUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description 회원가입 및 세션 생성 완료 */
      201: {
        headers: {
          /** @description 생성된 사용자 리소스 */
          Location?: string;
          'Set-Cookie': components['headers']['SessionCookie'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      400: components['responses']['BadRequest'];
      409: components['responses']['Conflict'];
      429: components['responses']['TooManyRequests'];
    };
  };
  createSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description 로그인 완료 */
      201: {
        headers: {
          'Set-Cookie': components['headers']['SessionCookie'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description 이메일 또는 비밀번호가 일치하지 않음 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "type": "https://api.example.invalid/problems/invalid-credentials",
           *       "title": "인증 실패",
           *       "status": 401,
           *       "detail": "이메일 또는 비밀번호를 확인해 주세요.",
           *       "code": "INVALID_CREDENTIALS",
           *       "requestId": "req_01J5D8M7Q4"
           *     }
           */
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      429: components['responses']['TooManyRequests'];
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 현재 사용자와 CSRF 토큰 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  deleteCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 로그아웃 완료 */
      204: {
        headers: {
          /** @description 만료된 세션 쿠키 */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 내 계정 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  deleteMe: {
    parameters: {
      query?: never;
      header: {
        'X-Confirm-Deletion': components['parameters']['DeleteConfirmation'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 전체 삭제 완료 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  completeOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingRequest'];
      };
    };
    responses: {
      /** @description 저장된 온보딩 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Onboarding'];
        };
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  getNotificationSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 알림 설정 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationSettings'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  updateNotificationSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          enabled?: boolean;
          time?: components['schemas']['NotificationTime'];
          consent?: components['schemas']['NotificationConsentInput'];
        };
      };
    };
    responses: {
      /** @description 변경된 알림 설정 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationSettings'];
        };
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  createPushSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePushSubscriptionRequest'];
      };
    };
    responses: {
      /** @description 동일 endpoint의 기존 구독 갱신 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PushSubscription'];
        };
      };
      /** @description 구독 등록 완료 */
      201: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PushSubscription'];
        };
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
      429: components['responses']['TooManyRequests'];
    };
  };
  deletePushSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subscriptionId: components['parameters']['SubscriptionId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 구독 해제 완료 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  getHome: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 홈 화면 집계 정보 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Home'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  saveNoDiscomfortCheckIn: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Asia/Seoul 기준 날짜 */
        date: components['parameters']['CheckInDate'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @constant */
          state: 'NO_DISCOMFORT';
        };
      };
    };
    responses: {
      /** @description 같은 값이 이미 저장되어 있음 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DailyCheckIn'];
        };
      };
      /** @description 불편 없음 저장 완료 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DailyCheckIn'];
        };
      };
      401: components['responses']['Unauthorized'];
      409: components['responses']['Conflict'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  getSkinReportOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 선택값 목록 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkinReportOptions'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  createReportInterpretation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InterpretReportRequest'];
      };
    };
    responses: {
      /** @description 구조화 결과 또는 수동 입력용 실패 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReportInterpretation'];
        };
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
      429: components['responses']['TooManyRequests'];
      503: components['responses']['ServiceUnavailable'];
    };
  };
  listSkinReports: {
    parameters: {
      query?: {
        /** @description createdAt과 id를 포함한 불투명 커서 */
        cursor?: components['parameters']['Cursor'];
        limit?: components['parameters']['Limit'];
        status?: components['schemas']['ReportStatus'];
        resultType?: components['schemas']['ResultType'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 최신순 기록 목록 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkinReportList'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  createSkinReport: {
    parameters: {
      query?: never;
      header: {
        /** @description 같은 사용자와 작업 범위에서 24시간 보관하는 UUID */
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSkinReportRequest'];
      };
    };
    responses: {
      /** @description 같은 Idempotency-Key 요청의 기존 응답 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkinReportDetail'];
        };
      };
      /** @description 피부 보고 및 결과 저장 완료 */
      201: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkinReportDetail'];
        };
      };
      401: components['responses']['Unauthorized'];
      409: components['responses']['Conflict'];
      422: components['responses']['UnprocessableEntity'];
      429: components['responses']['TooManyRequests'];
      503: components['responses']['ServiceUnavailable'];
    };
  };
  getSkinReport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 피부 기록 상세 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkinReportDetail'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  retryCareGuideGeneration: {
    parameters: {
      query?: never;
      header: {
        /** @description 같은 사용자와 작업 범위에서 24시간 보관하는 UUID */
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 재생성 결과 또는 동일 키의 기존 결과 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CareResult'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getFollowUp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저장된 경과 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FollowUp'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  saveFollowUp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reportId: components['parameters']['ReportId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveFollowUpRequest'];
      };
    };
    responses: {
      /** @description 동일 경과가 이미 저장되어 있음 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FollowUp'];
        };
      };
      /** @description 경과 저장 및 보고 COMPLETED 전환 완료 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FollowUp'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  createAnalyticsEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          events: components['schemas']['AnalyticsEventInput'][];
        };
      };
    };
    responses: {
      /** @description 이벤트 접수 완료 */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accepted: number;
          };
        };
      };
      401: components['responses']['Unauthorized'];
      422: components['responses']['UnprocessableEntity'];
      429: components['responses']['TooManyRequests'];
    };
  };
}
